version: '3.8'
services:
  frontend:
    build: ./frontend
    ports: ['3000:80']
    depends_on: ['backend']
  backend:
    build: ./backend
    ports: ['4000:4000']
  ml-service:
    build: ./ml-service
    ports: ['5000:5000']
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: skiroute3d
    ports: ['5432:5432']
  redis:
    image: redis:7
    ports: ['6379:6379']
